import { Categoria, Producto, Evento, ConfiguracionTV } from './types';

export const CATEGORIAS_INICIALES: Categoria[] = [
  { id: 'cat-burgers', nombre: 'Burgers + Papas', slug: 'burgers', orden: 1, icono: 'Flame', activo: true },
  { id: 'cat-sandwiches', nombre: 'Sandwiches', slug: 'sandwiches', orden: 2, icono: 'Sandwich', activo: true },
  { id: 'cat-chorrillanas', nombre: 'Chorrillanas', slug: 'chorrillanas', orden: 3, icono: 'Drumstick', activo: true },
  { id: 'cat-papas', nombre: 'Papas Fritas', slug: 'papas-fritas', orden: 4, icono: 'UtensilsCrossed', activo: true },
  { id: 'cat-completos', nombre: 'Completos & Ases', slug: 'completos', orden: 5, icono: 'Beef', activo: true },
  { id: 'cat-fajitas', nombre: 'Fajitas', slug: 'fajitas', orden: 6, icono: 'Wrap', activo: true },
  { id: 'cat-ensaladas', nombre: 'Ensaladas', slug: 'ensaladas', orden: 7, icono: 'Salad', activo: true },
  { id: 'cat-bebidas', nombre: 'Bebidas', slug: 'bebidas', orden: 8, icono: 'CupSoda', activo: true },
];

export const PRODUCTOS_INICIALES: Producto[] = [
  // --- BURGERS ---
  {
    id: 'b-1',
    categoria_id: 'cat-burgers',
    nombre: 'Hamburguesa Walala',
    descripcion: 'Doble Queso Cheddar, Doble Carne, Cebolla Caramelizada, Huevo, Tocino, Champiñón, Tomate, Palta, Mayo, Bbq, Mostaza y Ketchup',
    precio: 7000,
    imagen_url: '/images/395747bfb6d9559fbc5e6ce7c00e365e.jpg',
    disponible: true,
    es_destacado: true,
    mostrar_en_tv: true,
    pantalla_tv: 1,
    orden: 1,
  },
  {
    id: 'b-2',
    categoria_id: 'cat-burgers',
    nombre: 'Doble Sensación',
    descripcion: 'Doble Carne, Doble Queso Cheddar, Palta, Mayo, Bbq, Mostaza y Ketchup',
    precio: 6000,
    imagen_url: '/images/e88fb0a7c5f6a08ae9bba1aa294d8bb9.png',
    disponible: true,
    es_destacado: true,
    mostrar_en_tv: true,
    pantalla_tv: 1,
    orden: 2,
  },
  {
    id: 'b-3',
    categoria_id: 'cat-burgers',
    nombre: 'Hamburguesa Basqui',
    descripcion: 'Champiñón, Crema, Queso Cheddar, Queso gouda, Tocino, Bbq, Mostaza y Ketchup',
    precio: 6500,
    imagen_url: '/images/e88fb0a7c5f6a08ae9bba1aa294d8bb9.png',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 1,
    orden: 3,
  },
  {
    id: 'b-4',
    categoria_id: 'cat-burgers',
    nombre: 'Hamburguesa Tutty',
    descripcion: 'Queso, Champiñón, Tocino, Tomate, Palta, Mayo, Bbq, Mostaza y Ketchup',
    precio: 6000,
    imagen_url: '/images/395747bfb6d9559fbc5e6ce7c00e365e.jpg',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 1,
    orden: 4,
  },
  {
    id: 'b-5',
    categoria_id: 'cat-burgers',
    nombre: 'Hamburguesa Billy',
    descripcion: 'Queso Cheddar, Lechuga, Pepinillo, Tocino, Mayo, Bbq, Mostaza y Ketchup',
    precio: 5500,
    imagen_url: '/images/e88fb0a7c5f6a08ae9bba1aa294d8bb9.png',
    disponible: true,
    es_destacado: true,
    mostrar_en_tv: true,
    pantalla_tv: 1,
    orden: 5,
  },
  {
    id: 'b-6',
    categoria_id: 'cat-burgers',
    nombre: 'Hamburguesa Ju',
    descripcion: 'Tomate, Lechuga, Cebolla, Queso Cheddar, Salsa Gold más pepinillos',
    precio: 5500,
    imagen_url: '/images/e88fb0a7c5f6a08ae9bba1aa294d8bb9.png',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 1,
    orden: 6,
  },
  {
    id: 'b-7',
    categoria_id: 'cat-burgers',
    nombre: 'Hamburguesa Cheddar',
    descripcion: 'Queso Cheddar, Cebolla Caramelizada, Bbq, Mostaza y Ketchup',
    precio: 5000,
    imagen_url: '/images/e88fb0a7c5f6a08ae9bba1aa294d8bb9.png',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 1,
    orden: 7,
  },
  {
    id: 'b-8',
    categoria_id: 'cat-burgers',
    nombre: 'Hamburguesa Italiana',
    descripcion: 'Tomate, Palta, Mayo, Queso Cheddar, Bbq, Mostaza y Ketchup',
    precio: 5000,
    imagen_url: '/images/e88fb0a7c5f6a08ae9bba1aa294d8bb9.png',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 1,
    orden: 8,
  },
  {
    id: 'b-9',
    categoria_id: 'cat-burgers',
    nombre: 'Hamburguesa 1/4',
    descripcion: 'Pepinillo, Cebolla, Queso Cheddar, Bbq, Mostaza y Ketchup',
    precio: 5000,
    imagen_url: '/images/e88fb0a7c5f6a08ae9bba1aa294d8bb9.png',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 1,
    orden: 9,
  },
  {
    id: 'b-10',
    categoria_id: 'cat-burgers',
    nombre: 'Hamburguesa Veggie',
    descripcion: 'Champiñón, Zapallo Italiano o Huevo, Tomate, Palta, Mayo, Queso Cheddar, Bbq, Mostaza y Ketchup',
    precio: 5000,
    imagen_url: '/images/e88fb0a7c5f6a08ae9bba1aa294d8bb9.png',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 1,
    orden: 10,
  },

  // --- SANDWICHES ---
  {
    id: 's-1',
    categoria_id: 'cat-sandwiches',
    nombre: 'Churrasco a lo Pobre',
    descripcion: 'Carne, Huevo, Cebolla y Papas Fritas en el Sándwich',
    precio: 7000,
    precio_secundario: 5500,
    etiqueta_precio_secundario: 'Sin Papas',
    imagen_url: '/images/fe065dbf0412b66d90eeed1bf975c0b6.png',
    disponible: true,
    es_destacado: true,
    mostrar_en_tv: true,
    pantalla_tv: 2,
    orden: 1,
  },
  {
    id: 's-2',
    categoria_id: 'cat-sandwiches',
    nombre: 'Churrasco Miguelo',
    descripcion: 'Carne, Queso gouda y Palta',
    precio: 6500,
    precio_secundario: 5000,
    etiqueta_precio_secundario: 'Sin Papas',
    imagen_url: '/images/fe065dbf0412b66d90eeed1bf975c0b6.png',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 2,
    orden: 2,
  },
  {
    id: 's-3',
    categoria_id: 'cat-sandwiches',
    nombre: 'Sandwich Napolitano',
    descripcion: 'Churrasco, Tomate, Queso y Orégano',
    precio: 7000,
    precio_secundario: 5500,
    etiqueta_precio_secundario: 'Sin Papas',
    imagen_url: '/images/fe065dbf0412b66d90eeed1bf975c0b6.png',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 2,
    orden: 3,
  },
  {
    id: 's-4',
    categoria_id: 'cat-sandwiches',
    nombre: 'Sandwich Champiñón',
    descripcion: 'Churrasco, Queso gouda y Champiñón',
    precio: 7000,
    precio_secundario: 5500,
    etiqueta_precio_secundario: 'Sin Papas',
    imagen_url: '/images/fe065dbf0412b66d90eeed1bf975c0b6.png',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 2,
    orden: 4,
  },
  {
    id: 's-5',
    categoria_id: 'cat-sandwiches',
    nombre: 'Mechada Italiana',
    descripcion: 'Carne Mechada casera, Tomate, Palta y Mayo',
    precio: 6200,
    precio_secundario: 4700,
    etiqueta_precio_secundario: 'Sin Papas',
    imagen_url: '/images/fe065dbf0412b66d90eeed1bf975c0b6.png',
    disponible: true,
    es_destacado: true,
    mostrar_en_tv: true,
    pantalla_tv: 2,
    orden: 5,
  },
  {
    id: 's-6',
    categoria_id: 'cat-sandwiches',
    nombre: 'Mechada Queso',
    descripcion: 'Carne Mechada y abundante Queso gouda fundido',
    precio: 6200,
    precio_secundario: 4700,
    etiqueta_precio_secundario: 'Sin Papas',
    imagen_url: '/images/fe065dbf0412b66d90eeed1bf975c0b6.png',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 2,
    orden: 6,
  },
  {
    id: 's-7',
    categoria_id: 'cat-sandwiches',
    nombre: 'Mechada Chacarera',
    descripcion: 'Carne Mechada, Tomate, Palta, Mayo, Poroto Verde y Ají Verde',
    precio: 7000,
    precio_secundario: 5500,
    etiqueta_precio_secundario: 'Sin Papas',
    imagen_url: '/images/fe065dbf0412b66d90eeed1bf975c0b6.png',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 2,
    orden: 7,
  },
  {
    id: 's-8',
    categoria_id: 'cat-sandwiches',
    nombre: 'Churrasco Italiano',
    descripcion: 'Churrasco tierno, Tomate, Palta y Mayo',
    precio: 6200,
    precio_secundario: 4700,
    etiqueta_precio_secundario: 'Sin Papas',
    imagen_url: '/images/fe065dbf0412b66d90eeed1bf975c0b6.png',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 2,
    orden: 8,
  },
  {
    id: 's-9',
    categoria_id: 'cat-sandwiches',
    nombre: 'Churrasco Barros Luco',
    descripcion: 'Churrasco y abundante Queso gouda fundido',
    precio: 6200,
    precio_secundario: 4700,
    etiqueta_precio_secundario: 'Sin Papas',
    imagen_url: '/images/fe065dbf0412b66d90eeed1bf975c0b6.png',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 2,
    orden: 9,
  },
  {
    id: 's-10',
    categoria_id: 'cat-sandwiches',
    nombre: 'Pollo Italiano',
    descripcion: 'Pollo a la plancha, Tomate, Palta y Mayo',
    precio: 6200,
    precio_secundario: 4700,
    etiqueta_precio_secundario: 'Sin Papas',
    imagen_url: '/images/fe065dbf0412b66d90eeed1bf975c0b6.png',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 2,
    orden: 10,
  },

  // --- CHORRILLANAS ---
  {
    id: 'ch-1',
    categoria_id: 'cat-chorrillanas',
    nombre: 'Chorrillana Grande',
    descripcion: 'Papas Fritas crujientes, abundante carne, cebolla caramelizada y 2 huevos fritos (Ideal para compartir)',
    precio: 12500,
    imagen_url: '/images/21563c566950eabf31a360d208c462f3.png',
    disponible: true,
    es_destacado: true,
    mostrar_en_tv: true,
    pantalla_tv: 2,
    orden: 1,
  },
  {
    id: 'ch-2',
    categoria_id: 'cat-chorrillanas',
    nombre: 'Chorrillana Chica',
    descripcion: 'Papas Fritas, carne, cebolla caramelizada y huevo frito',
    precio: 6500,
    imagen_url: '/images/21563c566950eabf31a360d208c462f3.png',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 2,
    orden: 2,
  },
  {
    id: 'ch-3',
    categoria_id: 'cat-chorrillanas',
    nombre: 'Chorrillana Puma Grande',
    descripcion: 'Receta especial Puma con papas crujientes y mix exclusivo de ingredientes',
    precio: 9500,
    imagen_url: '/images/21563c566950eabf31a360d208c462f3.png',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 2,
    orden: 3,
  },
  {
    id: 'ch-4',
    categoria_id: 'cat-chorrillanas',
    nombre: 'Chorrillana Puma Chica',
    descripcion: 'Receta especial Puma en porción individual',
    precio: 5500,
    imagen_url: '/images/21563c566950eabf31a360d208c462f3.png',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 2,
    orden: 4,
  },

  // --- PAPAS FRITAS ---
  {
    id: 'p-1',
    categoria_id: 'cat-papas',
    nombre: 'Salchi Papa Grande',
    descripcion: 'Porción abundante de papas fritas doradas con vienesas salteadas',
    precio: 8500,
    imagen_url: '/images/3d75f978fb46740ea58ffba38bc4dff0.png',
    disponible: true,
    es_destacado: true,
    mostrar_en_tv: true,
    pantalla_tv: 1,
    orden: 1,
  },
  {
    id: 'p-2',
    categoria_id: 'cat-papas',
    nombre: 'Salchi Papa Chica',
    descripcion: 'Papas fritas con vienesas salteadas individual',
    precio: 5000,
    imagen_url: '/images/3d75f978fb46740ea58ffba38bc4dff0.png',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 1,
    orden: 2,
  },
  {
    id: 'p-3',
    categoria_id: 'cat-papas',
    nombre: 'Papa Frita Grande',
    descripcion: 'Porción familiar de papas fritas recién hechas',
    precio: 6000,
    imagen_url: '/images/3d75f978fb46740ea58ffba38bc4dff0.png',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 1,
    orden: 3,
  },
  {
    id: 'p-4',
    categoria_id: 'cat-papas',
    nombre: 'Papa Frita Mediana',
    descripcion: 'Porción para 2 personas',
    precio: 4000,
    imagen_url: '/images/3d75f978fb46740ea58ffba38bc4dff0.png',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 1,
    orden: 4,
  },
  {
    id: 'p-5',
    categoria_id: 'cat-papas',
    nombre: 'Papa Frita Chica',
    descripcion: 'Porción individual para acompañar',
    precio: 2000,
    imagen_url: '/images/3d75f978fb46740ea58ffba38bc4dff0.png',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 1,
    orden: 5,
  },

  // --- COMPLETOS & ASES ---
  {
    id: 'cp-1',
    categoria_id: 'cat-completos',
    nombre: 'AS Mechada o Churrasco',
    descripcion: 'Mechada o Churrasco con Tomate, Palta, Mayo o Queso gouda fundido',
    precio: 2800,
    imagen_url: '/images/fe065dbf0412b66d90eeed1bf975c0b6.png',
    disponible: true,
    es_destacado: true,
    mostrar_en_tv: true,
    pantalla_tv: 2,
    orden: 1,
  },
  {
    id: 'cp-2',
    categoria_id: 'cat-completos',
    nombre: 'Champipleto',
    descripcion: 'Champiñón, Tomate, Palta, Mayo o Champiñón con Queso gouda',
    precio: 2500,
    imagen_url: '/images/fe065dbf0412b66d90eeed1bf975c0b6.png',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 2,
    orden: 2,
  },
  {
    id: 'cp-3',
    categoria_id: 'cat-completos',
    nombre: 'Pollopleto',
    descripcion: 'Pollo a la plancha, Tomate, Palta, Mayo o Queso gouda',
    precio: 2500,
    imagen_url: '/images/fe065dbf0412b66d90eeed1bf975c0b6.png',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 2,
    orden: 3,
  },
  {
    id: 'cp-4',
    categoria_id: 'cat-completos',
    nombre: 'Completo Tradicional',
    descripcion: 'Tomate, Palta, Mayo, Chucrut y Salsa Americana',
    precio: 2200,
    imagen_url: '/images/fe065dbf0412b66d90eeed1bf975c0b6.png',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 2,
    orden: 4,
  },
  {
    id: 'cp-5',
    categoria_id: 'cat-completos',
    nombre: 'Completo Italiano',
    descripcion: 'Vienesa, Tomate en cubos, Palta fresca y Mayo',
    precio: 2000,
    imagen_url: '/images/fe065dbf0412b66d90eeed1bf975c0b6.png',
    disponible: true,
    es_destacado: true,
    mostrar_en_tv: true,
    pantalla_tv: 2,
    orden: 5,
  },
  {
    id: 'cp-6',
    categoria_id: 'cat-completos',
    nombre: 'Papapleto',
    descripcion: 'Papas Fritas, Tomate, Palta y Mayo',
    precio: 1700,
    imagen_url: '/images/fe065dbf0412b66d90eeed1bf975c0b6.png',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 2,
    orden: 6,
  },
  {
    id: 'cp-7',
    categoria_id: 'cat-completos',
    nombre: 'Panchito',
    descripcion: 'Pan de completo, Vienesa y Ketchup',
    precio: 1500,
    imagen_url: '/images/fe065dbf0412b66d90eeed1bf975c0b6.png',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 2,
    orden: 7,
  },

  // --- FAJITAS ---
  {
    id: 'f-1',
    categoria_id: 'cat-fajitas',
    nombre: 'Fajita Cedric',
    descripcion: 'Carne, Queso gouda fundido y Champiñón',
    precio: 4500,
    imagen_url: '/images/e620e6e57b48ffa58bbcc57c70050e8b.jpg',
    disponible: true,
    es_destacado: true,
    mostrar_en_tv: true,
    pantalla_tv: 2,
    orden: 1,
  },
  {
    id: 'f-2',
    categoria_id: 'cat-fajitas',
    nombre: 'Fajita Mixta',
    descripcion: 'Tomate, Palta, Mayo, Lechuga, Carne y Pollo',
    precio: 4500,
    imagen_url: '/images/e620e6e57b48ffa58bbcc57c70050e8b.jpg',
    disponible: true,
    es_destacado: true,
    mostrar_en_tv: true,
    pantalla_tv: 2,
    orden: 2,
  },
  {
    id: 'f-3',
    categoria_id: 'cat-fajitas',
    nombre: 'Fajita Carne o Pollo',
    descripcion: 'Tomate, Palta, Mayo, Lechuga, Carne o Pollo a elección',
    precio: 4000,
    imagen_url: '/images/e620e6e57b48ffa58bbcc57c70050e8b.jpg',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 2,
    orden: 3,
  },
  {
    id: 'f-4',
    categoria_id: 'cat-fajitas',
    nombre: 'Fajita Champiñón',
    descripcion: 'Tomate, Palta, Mayo, Lechuga y Champiñón',
    precio: 3500,
    imagen_url: '/images/e620e6e57b48ffa58bbcc57c70050e8b.jpg',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 2,
    orden: 4,
  },

  // --- ENSALADAS ---
  {
    id: 'e-1',
    categoria_id: 'cat-ensaladas',
    nombre: 'Ensalada Completa Billy',
    descripcion: 'Tomate, Palta, Lechuga fresca, Carne, Pollo, Papas Fritas y Huevo',
    precio: 5500,
    imagen_url: '/images/4029ddaca1b888b1ff20dcc96b615aac.png',
    disponible: true,
    es_destacado: true,
    mostrar_en_tv: true,
    pantalla_tv: 2,
    orden: 1,
  },

  // --- BEBIDAS ---
  {
    id: 'beb-1',
    categoria_id: 'cat-bebidas',
    nombre: 'Bebida 2 Litros',
    descripcion: 'Variedad de sabores (Coca-Cola, Sprite, Fanta)',
    precio: 2800,
    imagen_url: '/images/1ffa9750e1002b36fc52371703b341fb.png',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 0,
    orden: 1,
  },
  {
    id: 'beb-2',
    categoria_id: 'cat-bebidas',
    nombre: 'Bebida 1.5 Litros',
    descripcion: 'Variedad de sabores',
    precio: 2500,
    imagen_url: '/images/1ffa9750e1002b36fc52371703b341fb.png',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 0,
    orden: 2,
  },
  {
    id: 'beb-3',
    categoria_id: 'cat-bebidas',
    nombre: 'Jugo 2 Litros',
    descripcion: 'Sabores surtidos frutales',
    precio: 2000,
    imagen_url: '/images/1ffa9750e1002b36fc52371703b341fb.png',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 0,
    orden: 3,
  },
  {
    id: 'beb-4',
    categoria_id: 'cat-bebidas',
    nombre: 'Bebida en Lata 350cc',
    descripcion: 'Bien heladas, variedad Coca-Cola, Sprite, Fanta',
    precio: 1500,
    imagen_url: '/images/1ffa9750e1002b36fc52371703b341fb.png',
    disponible: true,
    es_destacado: true,
    mostrar_en_tv: true,
    pantalla_tv: 0,
    orden: 4,
  },
  {
    id: 'beb-5',
    categoria_id: 'cat-bebidas',
    nombre: 'Agua Mineral 500cc',
    descripcion: 'Con Gas o Sin Gas',
    precio: 1500,
    imagen_url: '/images/1ffa9750e1002b36fc52371703b341fb.png',
    disponible: true,
    es_destacado: false,
    mostrar_en_tv: true,
    pantalla_tv: 0,
    orden: 5,
  },
];

export const EVENTOS_INICIALES: Evento[] = [
  {
    id: 'ev-1',
    titulo: '¿Quieres que seamos parte de tu celebración?',
    descripcion: 'Cotiza con nosotros una experiencia llena de sabor. Cumpleaños, reuniones familiares y eventos de empresa con nuestro menú completo de hamburguesas y chorrillanas.',
    fecha_evento: 'Reservas disponibles',
    banner_url: '/images/395747bfb6d9559fbc5e6ce7c00e365e.jpg',
    mostrar_en_tv: true,
    activo: true,
    orden: 1,
  },
];

export const CONFIG_TV_INICIAL: ConfiguracionTV[] = [
  {
    pantalla_id: 1,
    nombre: 'Pantalla 1 - Burgers & Papas Fritas',
    segundos_rotacion: 12,
    cintillo_texto: '🔥 ¡Bienvenido a Billy Burger! Pide en caja o al WhatsApp +56 9 3255 3527 • Todas las burgers y sándwiches incluyen crujientes papas fritas',
  },
  {
    pantalla_id: 2,
    nombre: 'Pantalla 2 - Chorrillanas & Sándwiches',
    segundos_rotacion: 12,
    cintillo_texto: '🔥 Prueba nuestras Chorrillanas y Sándwiches XL • Eventos y celebraciones a pedido al +56 9 3255 3527',
  },
];
